Cats background
hawkrai/CATSdesigner pull request #507
Opened 2023-11-15 21:00 UTC by web-front-dev

2023-11-17 00:23 UTC, Mgarcia1996 approved these changes

2023-11-18 09:18 UTC, Arf287 approved these changes
T

2023-11-20 16:00 UTC, hawkrai requested changes

2023-11-20 16:00 UTC, hawkrai commented on container/src/app/login/login.component.less
> +// вынесение за рамки обшего класса
remove any russian comments

2023-11-20 17:08 UTC, hawkrai approved these changes

2023-11-20 17:08 UTC, merged