Fix/course project
hawkrai/CATSdesigner pull request #520
Opened 2023-12-16 20:02 UTC by SergeiMol

Ветка создана от этого МРа => https://github.com/hawkrai/CATSdesigner/pull/517

2023-12-19 12:51 UTC, web-front-dev commented
Нужно глянуть конфликты

2023-12-19 12:57 UTC, web-front-dev commented on modules/complex/src/app/store/effects/files.effects.ts
> -        this.filesService
Разве мы не отформатировали весь проект?

2023-12-24 16:34 UTC, SergeiMol commented on modules/complex/src/app/store/effects/files.effects.ts
> -        this.filesService
ну я спулил ветку с CLI, прогнал prettier и он эти файлы нашел

2023-12-26 20:33 UTC, hawkrai requested changes

2023-12-26 20:33 UTC, hawkrai commented on cli/README.md
we don't need cli from this PR

2023-12-27 08:51 UTC, SergeiMol commented on cli/README.md
поправил

2023-12-31 11:58 UTC, merged