feat: changing label in line
hawkrai/CATSdesigner pull request #552
Opened 2024-03-26 12:51 UTC by Ivan31321

2024-03-26 15:16 UTC, web-front-dev commented on modules/complex/src/app/complexMaterial/components/materials/add-material-popover/add-material-popover.component.html
> +          <!-- Handle branch node buttons here  -->
Ты линтеры устанавливал в корне проекта? Они должны такое править

2024-03-26 15:16 UTC, web-front-dev commented on modules/complex/src/app/complexMaterial/components/materials/add-material-popover/add-material-popover.component.html
> -
Тут аналогично, такое не должно проскакивать в pr

2024-03-27 11:28 UTC, hzhurauski approved these changes

2024-04-01 15:39 UTC, hawkrai requested changes
please pay attention to the comments

2024-04-06 14:17 UTC, merged