feat: add a close form button
hawkrai/CATSdesigner pull request #553
Opened 2024-03-26 19:17 UTC by Vladislav-Sharapa

2024-03-26 19:29 UTC, web-front-dev commented on modules/complex/src/app/complexMaterial/components/materials/adaptiveLearningPopup/adaptivePopup.component.html
> +    <span>{{
Ставил модули в корне проекта? Они должны такое переносить

2024-03-26 19:48 UTC, web-front-dev approved these changes

2024-04-01 15:39 UTC, hawkrai requested changes
please pay attention to the comments

2024-04-06 14:17 UTC, hawkrai approved these changes

2024-04-06 14:17 UTC, merged