style: optimization of the eumk editing form
hawkrai/CATSdesigner pull request #558
Opened 2024-03-29 16:53 UTC by NikitaZayatz

2024-03-29 16:56 UTC, web-front-dev commented on modules/complex/src/app/complexMaterial/components/materials/add-material-popover/add-material-popover.component.html
> +      <button class="close"   (click)="onClose(files, false)"><mat-icon>close</mat-icon></button>
Установи линтеры в корне проекта

2024-04-01 12:18 UTC, web-front-dev commented on modules/complex/src/app/complexMaterial/components/materials/add-material-popover/add-material-popover.component.html
> +      <button class="close"   (click)="onClose(files, false)"><mat-icon>close</mat-icon></button>
И после этого залей коммит с форматированием

2024-04-01 15:39 UTC, web-front-dev approved these changes

2024-04-01 15:39 UTC, hawkrai requested changes
please pay attention to the comments

2024-04-06 14:17 UTC, hawkrai approved these changes

2024-04-08 10:59 UTC, web-front-dev approved these changes

2024-04-09 13:22 UTC, closed without merging