style: made microphone and camera buttons in videochat visible
hawkrai/CATSdesigner pull request #569
Opened 2024-04-05 11:03 UTC by KSaRTgh

microphone and camera buttons were previously invisible in videochat

2024-04-05 11:15 UTC, hzhurauski commented on container/src/app/modules/video-chat/components/video-handler/video-handler.component.html
> +          <mat-icon class="control-icon" *ngIf="IsMicroActive" [ngStyle]="{ color: 'white' }">mic</mat-icon>
Давай через css, а не стили

2024-04-05 12:28 UTC, web-front-dev approved these changes

2024-04-06 14:20 UTC, hawkrai requested changes

2024-04-06 14:20 UTC, hawkrai commented on container/src/app/modules/video-chat/components/video-handler/video-handler.component.html
> +          <mat-icon class="control-icon" *ngIf="IsMicroActive" [ngStyle]="{ color: 'white' }">mic</mat-icon>
fix this

2024-04-15 10:36 UTC, web-front-dev commented on container/src/app/modules/video-chat/components/video-handler/video-handler.component.html
> +          <mat-icon class="control-icon" *ngIf="IsMicroActive" [ngStyle]="{ color: 'white' }">mic</mat-icon>
По словам Степы - стили работают корректно только в таком варианте

2024-04-15 10:37 UTC, hzhurauski approved these changes

2024-04-15 18:25 UTC, merged