Code formatting
hawkrai/CATSdesigner pull request #672
Opened 2024-07-04 12:10 UTC by zhur4k

2024-07-04 13:53 UTC, web-front-dev approved these changes

2024-07-08 19:04 UTC, hawkrai requested changes

2024-07-08 19:04 UTC, hawkrai commented on common/assets/styles/bootstrap.min.css
> +  transition:
Don't touch library files

2024-07-08 19:24 UTC, zhur4k commented on common/assets/styles/bootstrap.min.css
> +  transition:
![Uploading image.png…]()

2024-07-09 10:51 UTC, zhur4k commented on common/assets/styles/bootstrap.min.css
> +  transition:
ecd4b81f16bb80bc752660eae1f83d9e570734cc

2024-10-27 11:22 UTC, closed without merging